name: 'Docker'
on:
  pull_request:
    types:
      - closed
    branches:    
      - 'omolade-ci'
env:
  DOCKERHUB_USERNAME: ramirezgael030881
  DOCKERHUB_TOKEN: Holaquehaces2.000
  REPOSITORY_NAME: servidores
jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ramirezgael030881          
          password: Holaquehaces2.000
            
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}
      - name: Push Docker Image to Docker Hub
        run: docker push ramirezgael030881/servidores:${{ steps.date.outputs.date }}
